sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.1
before_install: gem install bundler -v 1.12.5

after_script:
  - bin/tukune --title 'Pull Request Title' --body 'Pull Request Body'

notifications:
  email: false
