sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.1
before_install:
  - gem install bundler -v 1.12.5
  - chmod +x bin/tukune

script:
  - bundle exec rake
  - bundle exec rubocop

after_failure:
  - bundle exec rubocop --auto-correct
  - bin/tukune --title '[BOT]bundle exec rubocop --auto-correct' --body 'This pull request made by tukune'

notifications:
  email: false
